name: Dynamic Path Filter Generator
description: Generates YAML filters for dorny/paths-filter based on marker files
author: Your name

branding:
  icon: filter
  color: blue

inputs:
  pattern:
    description: 'Glob pattern that matches directory. If the pattern does not end with a slash, it will be appended automatically.'
    required: true
  if-exists:
    description: 'The marker file that must exist in the directory. If not provided, all directories matching the pattern will be included.'
    required: false
  pattern-suffix:
    description: 'The pattern to append to the directory name'
    required: false
    default: '/**'

outputs:
  filter:
    description: 'The generated YAML filter string'

runs:
  using: node20
  main: dist/index.js
