name: Dynamic Path Filter Generator
description: Generates YAML filters for dorny/paths-filter based on marker files
author: Your name

branding:
  icon: filter
  color: blue

inputs:
  marker-file:
    description: 'The name of the marker file to look for'
    required: false
    default: 'Taskfile.yaml'
  pattern-suffix:
    description: 'The pattern to append to the directory name'
    required: false
    default: '/**'

outputs:
  filter:
    description: 'The generated YAML filter string'

runs:
  using: node20
  main: dist/index.js
