name: Test Workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate filter
        id: filter
        uses: ./
        with:
          marker-file: CustomMarker.yaml
          pattern-suffix: /*.js
      
      - name: Print filter
        run: echo "${{ steps.filter.outputs.filter }}"
